version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: travelmind-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travelmind-flask
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/travelmind
      - JWT_SECRET=travelmindsecret
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
