services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travelmind-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - ALLOWED_ORIGINS=http://localhost,http://127.0.0.1
    networks:
      - travelmind-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: travelmind-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - travelmind-network

networks:
  travelmind-network:
    driver: bridge
