services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travelmind-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - travelmind-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: travelmind-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - travelmind-network

networks:
  travelmind-network:
    driver: bridge
